import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import ConversationalProductDiscovery from "@/components/features/conversational-product-discovery";
import SmartCartOptimizer from "@/components/features/smart-cart-optimizer";
import AutoGeneratedListings from "@/components/features/auto-generated-listings";
import SmartPricingAssistant from "@/components/features/smart-pricing-assistant";
import AiChatbot from "@/components/features/ai-chatbot";
import { Search, ShoppingCart, FileText, DollarSign, MessageSquare } from "lucide-react";

export default function HomePage() {
  const features = [
    {
      value: "product-discovery",
      label: "Product Discovery",
      icon: <Search className="mr-2 h-5 w-5" />,
      component: <ConversationalProductDiscovery />,
      description: "Find products using natural language."
    },
    {
      value: "cart-optimizer",
      label: "Cart Optimizer",
      icon: <ShoppingCart className="mr-2 h-5 w-5" />,
      component: <SmartCartOptimizer />,
      description: "Optimize your cart for best value."
    },
    {
      value: "listing-generator",
      label: "Listing Generator",
      icon: <FileText className="mr-2 h-5 w-5" />,
      component: <AutoGeneratedListings />,
      description: "Auto-generate product listings."
    },
    {
      value: "pricing-assistant",
      label: "Pricing Assistant",
      icon: <DollarSign className="mr-2 h-5 w-5" />,
      component: <SmartPricingAssistant />,
      description: "Get smart pricing suggestions."
    },
    {
      value: "ai-chatbot",
      label: "AI Chatbot",
      icon: <MessageSquare className="mr-2 h-5 w-5" />,
      component: <AiChatbot />,
      description: "Automated customer support."
    },
  ];

  return (
    <div className="w-full max-w-5xl mx-auto py-8">
      <Tabs defaultValue={features[0].value} className="w-full">
        <TabsList className="grid w-full grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2 mb-6 h-auto p-1.5">
          {features.map((feature) => (
            <TabsTrigger 
              key={feature.value} 
              value={feature.value} 
              className="flex-col sm:flex-row items-center justify-center h-auto py-2.5 px-3 data-[state=active]:shadow-lg data-[state=active]:bg-primary/10 data-[state=active]:text-primary data-[state=active]:border-primary/50 data-[state=active]:border-b-2"
            >
              {feature.icon}
              <span className="mt-1 sm:mt-0 text-xs sm:text-sm text-center sm:text-left leading-tight">{feature.label}</span>
            </TabsTrigger>
          ))}
        </TabsList>
        {features.map((feature) => (
          <TabsContent key={feature.value} value={feature.value} className="mt-0">
            {feature.component}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
